import type { Metadata } from "next";
import { Goldman } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Container from "@/components/Container";
import Image from "next/image";
import Footer from "@/components/Footer";

const inter = Goldman({ subsets: ["latin"] , weight:['400']});

export const metadata: Metadata = {
  title: "Home | Europe Professional Training",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <Container>
          <div className="absolute w-[90px] h-[62px] lg:w-[222px] lg:h-[143px]  lg:top-[16.5px]  md:left-2 left-3">
            <Image priority fill quality={95} src="/footer.png" alt="logo" />
          </div>
          <div className=" absolute w-[45px] h-[29px] top-[16.5px] md:right-2 right-3">
            <Image src="/almamlaka.png" alt="logo" width={45} height={29}/>
          </div>
        </Container>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
